intervals:
    submission_interval_hours: 24
    sleep_interval_seconds: 1200
subreddits:
  - FAUbot
user_agents:
    debug: &debug "/u/{username} prototyping a Reddit bot class"
    ExampleBot1: *debug
    ExampleBot2: *debug
    NewsBot: "/u/{username} submitting links from upressonline.com"
    EventBot: "/u/{username} creating a live FAU event calendar in a self post"
    TicketBot: "/u/{username} matching buyers and sellers of graduation tickets"
flags:
    run_bots_once: False
