intervals:
    submission_interval_hours: 24
    sleep_interval_seconds: 1200
subreddits:
  - FAUbot
user_agents:
    debug: &debug "/u/FAUbot prototyping a Reddit bot class"
    ExampleBot1: *debug
    ExampleBot2: *debug
    NewsBot: "/u/FAUbot submitting links from upressonline.com"
    EventBot: "/u/FAUbot creating a live FAU event calendar in a self post"
    TicketBot: "/u/FAUbot matching buyers and sellers of graduation tickets"
flags:
    run_bots_once: False
