intervals:
    submission_interval_hours: 24
    sleep_interval_seconds: 10
subreddits:
  - FAUbot
user_agents:
    debug: &debug "/u/FAUbot prototyping a Reddit bot class"
    ExampleBot1: *debug
    ExampleBot2: *debug
    NewsBot: "/u/FAUbot submitting links from upressonline.com"
flags:
    run_bots_once: False
